# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
    command: ["./main"]
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: yordi
      MONGO_INITDB_ROOT_PASSWORD: 123456taskmanager
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
